### ISSUE TITLE
TypeError: type.toUpperCase is not a function

### ISSUE THREAD

**Issue by seemsindie** [iam4x/isomorphic-flux-boilerplate#108]
When i added 'npm i material-ui --save' and included it like:

    import RaisedButton from 'material-ui';
    import Styles from 'material-ui';

    let ThemeManager = new Styles.ThemeManager();
    ThemeManager.setTheme(ThemeManager.types.DARK);

I am getting this error in the console:

    koa TypeError: type.toUpperCase is not a function
        at autoGenerateWrapperClass (/home/ivan/Projects/Personal/app/node_modules/react/lib/ReactDefaultInjection.js:53:19)
        at Object.getComponentClassForElement (/home/ivan/Projects/Personal/app/node_modules/react/lib/ReactNativeComponent.js:59:49)
        at validatePropTypes (/home/ivan/Projects/Personal/app/node_modules/react/lib/ReactElementValidator.js:361:45)
        at Object.ReactElementValidator.createElement (/home/ivan/Projects/Personal/app/node_modules/react/lib/ReactElementValidator.js:408:5)
        at Users.render (/home/ivan/Projects/Personal/app/app/components/users.jsx:100:11)
        at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/home/ivan/Projects/Personal/app/node_modules/react/lib/ReactCompositeComponent.js:789:34)
        at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/home/ivan/Projects/Personal/app/node_modules/react/lib/ReactCompositeComponent.js:816:14)
        at [object Object].wrapper [as _renderValidatedComponent] (/home/ivan/Projects/Personal/app/node_modules/react/lib/ReactPerf.js:70:21)
        at [object Object].ReactCompositeComponentMixin.mountComponent (/home/ivan/Projects/Personal/app/node_modules/react/lib/ReactCompositeComponent.js:237:30)
        at [object Object].wrapper [as mountComponent] (/home/ivan/Projects/Personal/app/node_modules/react/lib/ReactPerf.js:70:21)
        at Object.ReactReconciler.mountComponent (/home/ivan/Projects/Personal/app/node_modules/react/lib/ReactReconciler.js:38:35) +0ms

Do you know why and how to fix it?

**Comment by dmitry** [comment]
Looks like you have some issue on the line 100 (`users.jsx:100`).

**Comment by seemsindie** [comment]
On line 100 i just have <RaisedButton Label="Default button" />

**Comment by dmitry** [comment]
Might be an issue with attribute name `Label`

Also may be you wanted to:

```
import {RaisedButton, Styles} from 'material-ui'
```
