### ISSUE TITLE
isomorphic-flux-boilerplate@0.2.0 Failed to exec dev script

### ISSUE THREAD

**Issue by aauberg** [iam4x/isomorphic-flux-boilerplate#133]
I am setting up a new project from a working repo. The dev-script on my other machine is identical to this one, so I am not sure where to look next. Does anyone have a suggestion?
Contents of my npm-debug.log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev isomorphic-flux-boilerplate@0.2.0
6 info dev isomorphic-flux-boilerplate@0.2.0
7 verbose unsafe-perm in lifecycle true
8 info isomorphic-flux-boilerplate@0.2.0 Failed to exec dev script
9 verbose stack Error: isomorphic-flux-boilerplate@0.2.0 dev: `BABEL_ENV=browser NODE_ENV=development babel-node ./webpack/dev-server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid isomorphic-flux-boilerplate@0.2.0
11 verbose cwd /home/aaron/Repos/smart-spray-portal
12 error Linux 3.19.0-31-generic
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
14 error node v4.2.1
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error isomorphic-flux-boilerplate@0.2.0 dev: `BABEL_ENV=browser NODE_ENV=development babel-node ./webpack/dev-server.js`
17 error Exit status 1
18 error Failed at the isomorphic-flux-boilerplate@0.2.0 dev script 'BABEL_ENV=browser NODE_ENV=development babel-node ./webpack/dev-server.js'.
18 error This is most likely a problem with the isomorphic-flux-boilerplate package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     BABEL_ENV=browser NODE_ENV=development babel-node ./webpack/dev-server.js
18 error You can get their info via:
18 error     npm owner ls isomorphic-flux-boilerplate
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by aauberg** [comment]
This issue was solved by running
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p` 
per  http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc
