### ISSUE TITLE
Babel plugin error

### ISSUE THREAD

**Issue by hazybluedot** [iam4x/isomorphic-flux-boilerplate#154]
On a fresh clone, after running `npm install` attempting to run `npm run dev` results in an error

````
$ npm run dev

> isomorphic-flux-boilerplate@0.3.0 dev /path/to/app
> babel-node ./webpack/dev-server.js

/path/to/app/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164
      throw new TypeError(messages.get("pluginNotTransformer", name));
      ^

TypeError: The plugin "transform-react-jsx" didn't export a Plugin instance
    at PluginManager.validate (/path/to/app/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/path/to/app/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/path/to/app/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/path/to/app/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/path/to/app/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Object.transformFileSync (/path/to/app/node_modules/babel-core/lib/api/node.js:137:37)
    at compile (/path/to/app/node_modules/babel-core/lib/api/register/node.js:132:20)
    at normalLoader (/path/to/app/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/path/to/app/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
````

I have tried forcing versions of babel to those of another working version from an earlier clone but that doesn't resolve the issue. I have attached the output of npm list for reference. Unfortunately I am very new to babel and am still confused over the different versions and plugin behavior, so I'm not quite sure where to start debugging this.
[packages.list.txt](https://github.com/iam4x/isomorphic-flux-boilerplate/files/43028/packages.list.txt)

**Comment by iam4x** [comment]
What is your node version and npm version?

**Comment by hazybluedot** [comment]
Thanks for the reply, here are the versions of node and npm I am using:

````
$ node --version
v4.2.2
$ npm --version
2.14.7
````

**Comment by iam4x** [comment]
I can't reproduce it with fresh clone and npm install. What OS are you running?

**Comment by hazybluedot** [comment]
I'm running Fedora 23. That prompted me to create another fresh clone and that seems to be working now. The other one I had cloned into a subdirectory of an existing node project (because I had planned on porting that project over to this boilerplate) and perhaps that caused the problem. All is well, and now I know not to clone node projects into sub-directories of other node projects!

**Comment by mik01aj** [comment]
I have the same problem, tried `rm -r node_modules; npm cache clean; npm install` - didn't help.

Using node 4.2.0, npm 2.14.7, babel 5.8.23, babel-plugin-transform-react-jsx@6.3.13.

**Comment by mik01aj** [comment]
But updating Babel to v6 **did** help.
