### ISSUE TITLE
parse error in spinner.scss

### ISSUE THREAD

**Issue by cl1ck** [iam4x/isomorphic-flux-boilerplate#16]
"npm run dev" throws the following error running io.js v1.7.1 on OSX

```
> isomorphic-flux-boilerplate@0.1.0 dev /Users/rdg/repos/isomorphic-flux-boilerplate
> DEBUG=dev,koa node ./webpack/dev-server.js

  dev `webpack-dev-server` listen on port 3001 +0ms
  dev `webpack-stats.json` updated +7s
Time: 6570ms
                      Asset     Size  Chunks             Chunk Names
                1h0uCyf.eot  21.4 kB          [emitted]  
                YXLsN8c.svg  71.8 kB          [emitted]  
                2J_BsMc.ttf  45.3 kB          [emitted]  
               3sk6Jfr.woff    25 kB          [emitted]  
                V2d-uc_.png    49 kB          [emitted]  
app-7d6827f12e2cc4f9a70a.js  4.33 MB       0  [emitted]  app
webpack: bundle is now VALID.
/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/babel/helpers/parse.js:70
    throw err;
          ^
SyntaxError: /Users/rdg/repos/isomorphic-flux-boilerplate/app/styles/spinner.scss: Unexpected token (1:0)
> 1 | .app--spinner {
    | ^
  2 |   background-image: url('../images/spinner.svg');
  3 |   background-repeat: no-repeat;
  4 |   display: none;
    at Parser.pp.raise (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/src/location.js:68:13)
    at Parser.pp.unexpected (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/src/parseutil.js:87:8)
    at Parser.pp.parseExprAtom (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/src/expression.js:373:12)
    at Parser.parseExprAtom (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/plugins/jsx.js:593:162)
    at Parser.pp.parseExprSubscripts (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/src/expression.js:217:19)
    at Parser.pp.parseMaybeUnary (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/src/expression.js:199:19)
    at Parser.pp.parseExprOps (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/src/expression.js:155:19)
    at Parser.pp.parseMaybeConditional (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/src/expression.js:138:19)
    at Parser.pp.parseMaybeAssign (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/src/expression.js:106:19)
    at Parser.pp.parseExpression (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/src/expression.js:81:19)
```

**Comment by iam4x** [comment]
I haven't tried with new iojs yet, will look into it today!

**Comment by iam4x** [comment]
What is failing? Please try these two commands:

* `$ npm run build`
* `$ DEBUG=koa,dev node server/index.js`

It will help for investigation

**Comment by cl1ck** [comment]
Running node manually after build throws the same error:
```
~/r/isomorphic-flux-boilerplate git:master ❯❯❯ npm run build

> isomorphic-flux-boilerplate@0.1.0 build /Users/rdg/repos/isomorphic-flux-boilerplate
> webpack --progress --stats --config ./webpack/prod.config.js

Hash: 0b3984d35721da04b3c2  
Version: webpack 1.8.4
Time: 15086ms
                          Asset     Size  Chunks             Chunk Names
                    1h0uCyf.eot  21.4 kB          [emitted]  
                    2J_BsMc.ttf  45.3 kB          [emitted]  
                   3sk6Jfr.woff    25 kB          [emitted]  
                    1WcCD66.png  42.4 kB          [emitted]  
    app-0b3984d35721da04b3c2.js   306 kB       0  [emitted]  app
   app-0b3984d35721da04b3c2.css  4.29 kB       0  [emitted]  app
app-0b3984d35721da04b3c2.js.map  3.27 MB       0  [emitted]  app
    + 318 hidden modules
Child extract-text-webpack-plugin:
        + 3 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 6 hidden modules
Child extract-text-webpack-plugin:
        + 3 hidden modules
~/r/isomorphic-flux-boilerplate git:master ❯❯❯ DEBUG=koa,dev node server/index.js
/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/babel/helpers/parse.js:70
    throw err;
          ^
SyntaxError: /Users/rdg/repos/isomorphic-flux-boilerplate/app/styles/spinner.scss: Unexpected token (1:0)
> 1 | .app--spinner {
    | ^
  2 |   background-image: url('../images/spinner.svg');
  3 |   background-repeat: no-repeat;
  4 |   display: none;
    at Parser.pp.raise (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/src/location.js:68:13)
    at Parser.pp.unexpected (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/src/parseutil.js:87:8)
    at Parser.pp.parseExprAtom (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/src/expression.js:373:12)
    at Parser.parseExprAtom (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/plugins/jsx.js:593:162)
    at Parser.pp.parseExprSubscripts (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/src/expression.js:217:19)
    at Parser.pp.parseMaybeUnary (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/src/expression.js:199:19)
    at Parser.pp.parseExprOps (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/src/expression.js:155:19)
    at Parser.pp.parseMaybeConditional (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/src/expression.js:138:19)
    at Parser.pp.parseMaybeAssign (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/src/expression.js:106:19)
    at Parser.pp.parseExpression (/Users/rdg/repos/isomorphic-flux-boilerplate/node_modules/babel-core/lib/acorn/src/expression.js:81:19)
```

**Comment by cl1ck** [comment]
Just downgraded iojs to 1.6.3 and it throws the same error.

**Comment by iam4x** [comment]
Do you set `process.env.BROWSER` to true in your server code? Seems like node is trying to require the styles files, it shouldn't. 

See: https://github.com/iam4x/isomorphic-flux-boilerplate/blob/master/app/components/shared/spinner.jsx#L9-L11

**Comment by cl1ck** [comment]
The error appears even after fetching a clean copy of this repo. `process.env.BROWSER` resolves to `open` in spinner.jsx, which seems to be the reason why node includes the style files. No idea why, though.

**Comment by iam4x** [comment]
if you set `process.env.BROWSER = false` on first line of `server/index.js` does it works? Might be something wrong with your env variables :/

**Comment by cl1ck** [comment]
Didn't work :(
In spinner.jsx `process.env.BROWSER` resolves to `String('false')` which is true.

**Comment by iam4x** [comment]
Try: `BROWSER=false DEBUG=koa,dev node server/index.js`

**Comment by iam4x** [comment]
Any news @cl1ck ?

**Comment by cl1ck** [comment]
Yep, did a clean copy and unfortunately the result is still the same....

**Comment by iam4x** [comment]
Can you paste me the output of `$ env` ? I might have found something.

**Comment by cl1ck** [comment]
```
{  
   "NODE_ENV":"development",
   "DEBUG":"dev,koa",
   "npm_config_save_dev":"",
   "npm_package_dependencies_koa_etag":"^2.0.0",
   "npm_package_dependencies_koa_conditional_get":"^1.0.2",
   "GREP_COLOR":"37;45",
   "npm_config_viewer":"man",
   "npm_config_browser":"",
   "npm_package_gitHead":"b4093ea29c025a7dcc1f6d9e162e195559c9b131",
   "MANPATH":"/Users/rdg/.nvm/versions/io.js/v1.6.3/share/man:/usr/local/share/man:/Users/rdg/.node/share/man:/usr/share/man:/opt/X11/share/man:/usr/local/git/share/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man",
   "npm_package_dependencies_koa_static_cache":"^3.1.0",
   "LESS_TERMCAP_mb":"\u001b[01;31m",
   "NVM_IOJS_ORG_VERSION_LISTING":"https://iojs.org/dist/index.tab",
   "npm_config_rollback":"true",
   "npm_package_devDependencies_url_loader":"^0.5.5",
   "TERM_PROGRAM":"Apple_Terminal",
   "NODE":"/Users/rdg/.nvm/versions/io.js/v1.6.3/bin/iojs",
   "npm_config_usage":"",
   "npm_package_devDependencies_file_loader":"^0.8.1",
   "LESS_TERMCAP_md":"\u001b[01;31m",
   "npm_package_homepage":"https://github.com/iam4x/isomorphic-flux-boilerplate",
   "LESS_TERMCAP_me":"\u001b[0m",
   "npm_config_globalignorefile":"/Users/rdg/.node/etc/npmignore",
   "npm_package_keywords_19":"async",
   "npm_package_devDependencies_mocha":"^2.2.1",
   "SHELL":"/bin/zsh",
   "TERM":"xterm-256color",
   "npm_config_shell":"/bin/zsh",
   "npm_config_init_author_url":"",
   "npm_package_keywords_18":"hot-loader",
   "npm_package_devDependencies_style_loader":"^0.10.1",
   "npm_config_shrinkwrap":"true",
   "npm_config_parseable":"",
   "npm_package_keywords_17":"react-hot-loader",
   "npm_package_devDependencies_node_watch":"^0.3.4",
   "npm_package_devDependencies_babel":"^5.1.8",
   "npm_package_dependencies_koa":"^0.19.0",
   "TMPDIR":"/var/folders/dm/mw0ts40n7nj8nks0sg41hc500000gn/T/",
   "npm_config_init_license":"ISC",
   "npm_package_keywords_16":"react-router",
   "Apple_PubSub_Socket_Render":"/private/tmp/com.apple.launchd.uX0WZ6xqNW/Render",
   "NVM_PATH":"/Users/rdg/.nvm/versions/io.js/v1.6.3/lib/node",
   "npm_config_if_present":"",
   "npm_package_keywords_15":"jscs",
   "npm_package_devDependencies_babel_core":"^5.1.8",
   "npm_package_dependencies_debug":"^2.1.3",
   "TERM_PROGRAM_VERSION":"343.7",
   "npm_package_keywords_14":"eslint",
   "npm_package_scripts_dev":"DEBUG=dev,koa node ./webpack/dev-server.js",
   "npm_config_sign_git_tag":"",
   "npm_config_init_author_email":"",
   "npm_config_cache_max":"Infinity",
   "npm_package_keywords_13":"scss",
   "npm_package_devDependencies_sass_loader":"^0.4.2",
   "npm_config_long":"",
   "npm_config_local_address":"",
   "npm_config_git_tag_version":"true",
   "npm_config_cert":"",
   "npm_package_keywords_12":"sass",
   "npm_package_dependencies_superagent":"^1.1.0",
   "TERM_SESSION_ID":"0626B7CD-5F90-4EBC-9EAA-11C75F200F57",
   "LESS_TERMCAP_ue":"\u001b[0m",
   "npm_config_registry":"https://registry.npmjs.org/",
   "npm_config_npat":"",
   "npm_config_fetch_retries":"2",
   "npm_package_keywords_11":"babel",
   "npm_package_devDependencies_isparta_loader":"^0.2.0",
   "npm_package_dependencies_koa_response_time":"^1.0.2",
   "npm_package_keywords_10":"es6",
   "npm_package_devDependencies_jscs_loader":"0.0.5",
   "npm_package_devDependencies_extract_text_webpack_plugin":"^0.5.0",
   "npm_package_repository_url":"https://github.com/iam4x/isomorphic-flux-boilerplate.git",
   "npm_config_versions":"",
   "npm_config_message":"%s",
   "npm_config_key":"",
   "npm_package_readmeFilename":"README.md",
   "npm_package_tags_12":"sass",
   "npm_package_tags_7":"koa",
   "npm_package_dependencies_cookies_js":"^1.2.1",
   "npm_package_tags_13":"scss",
   "npm_package_tags_6":"ssr",
   "npm_package_devDependencies_webpack":"^1.5.3",
   "npm_package_description":"An ES6 isomorphic Flux/ReactJS boilerplate",
   "USER":"rdg",
   "NVM_DIR":"/Users/rdg/.nvm",
   "npm_package_tags_10":"es6",
   "npm_package_tags_5":"spa",
   "npm_package_license":"MIT",
   "LS_COLORS":"di=34:ln=35:so=32:pi=33:ex=31:bd=36;01:cd=33;01:su=31;40;07:sg=36;40;07:tw=32;40;07:ow=33;40;07:",
   "npm_package_tags_11":"babel",
   "npm_package_tags_4":"isomorphic",
   "npm_package_devDependencies_eslint_loader":"^0.10.0",
   "npm_package_dependencies_lru_cache":"^2.5.0",
   "GREP_COLORS":"mt=37;45",
   "npm_config_globalconfig":"/Users/rdg/.node/etc/npmrc",
   "npm_package_tags_16":"react-router",
   "npm_package_tags_3":"iso",
   "npm_package_devDependencies_karma":"^0.12.31",
   "npm_config_always_auth":"",
   "npm_package_tags_17":"react-hot-loader",
   "npm_package_tags_2":"alt",
   "npm_package_devDependencies_webpack_dev_server":"^1.7.0",
   "npm_package_tags_14":"eslint",
   "npm_package_tags_1":"flux",
   "npm_package_devDependencies_babel_loader":"^5.0.0",
   "npm_package_dependencies_lodash":"^3.6.0",
   "npm_package_dependencies_alt":"^0.15.3",
   "SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.78Pkqj7KFw/Listeners",
   "npm_config_spin":"true",
   "npm_package_tags_15":"jscs",
   "npm_package_tags_0":"react",
   "npm_package_devDependencies_eslint":"^0.19.0",
   "npm_package_dependencies_koa_logger":"^1.2.2",
   "__CF_USER_TEXT_ENCODING":"0x1F5:0x0:0x0",
   "npm_execpath":"/Users/rdg/.nvm/versions/io.js/v1.6.3/lib/node_modules/npm/bin/npm-cli.js",
   "npm_config_cache_lock_retries":"10",
   "npm_config_cafile":"",
   "npm_package_dependencies_koa_proxy":"^0.2.0",
   "PAGER":"less",
   "npm_package_tags_18":"hot-loader",
   "npm_package_devDependencies_autoprefixer_loader":"^1.2.0",
   "npm_package_author_name":"iam4x",
   "npm_config_heading":"npm",
   "npm_package_tags_19":"async",
   "LESS_TERMCAP_us":"\u001b[01;32m",
   "LSCOLORS":"exfxcxdxbxGxDxabagacad",
   "npm_config_proprietary_attribs":"true",
   "npm_config_fetch_retry_mintimeout":"10000",
   "npm_package_devDependencies_karma_coveralls":"^0.1.5",
   "npm_package_dependencies_koa_hbs":"^0.7.0",
   "npm_package_dependencies_intl":"^0.1.4",
   "npm_config_json":"",
   "npm_config_access":"",
   "npm_config_argv":"{\"remain\":[],\"cooked\":[\"run\",\"dev\"],\"original\":[\"run\",\"dev\"]}",
   "npm_package_devDependencies_karma_coverage":"^0.3.0",
   "npm_package_scripts_postinstall":"npm run build",
   "PATH":"/Users/rdg/.nvm/versions/io.js/v1.6.3/lib/node_modules/npm/bin/node-gyp-bin:/Users/rdg/repos/isoflux/node_modules/.bin:/Users/rdg/.nvm/versions/io.js/v1.6.3/bin:/usr/local/bin:/usr/local/sbin:/Users/rdg/bin:/Users/rdg/.node/bin:/Users/rdg/.composer/vendor/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/MAMP/bin/php/php5.5.10/bin:/opt/X11/bin:/usr/local/git/bin",
   "npm_package_tags_9":"jsx",
   "npm_package_dependencies_koa_mount":"^1.3.0",
   "npm_config_https_proxy":"",
   "npm_config_engine_strict":"",
   "npm_config_description":"true",
   "npm_package_tags_8":"webpack",
   "npm_config_userconfig":"/Users/rdg/.npmrc",
   "npm_config_init_module":"/Users/rdg/.npm-init.js",
   "npm_package_keywords_22":"es7",
   "npm_package_keywords_4":"isomorphic",
   "npm_package_devDependencies_karma_chrome_launcher":"^0.1.7",
   "npm_package_devDependencies_json_loader":"^0.5.1",
   "npm_package_dependencies_koa_helmet":"0.0.3",
   "NVM_NODEJS_ORG_MIRROR":"https://nodejs.org/dist",
   "npm_package_keywords_23":"i18n",
   "npm_package_keywords_5":"spa",
   "PWD":"/Users/rdg/repos/isoflux",
   "npm_config_user":"501",
   "npm_config_node_version":"1.6.3",
   "npm_package_keywords_20":"server",
   "npm_package_keywords_6":"ssr",
   "npm_package_bugs_url":"https://github.com/iam4x/isomorphic-flux-boilerplate/issues",
   "npm_lifecycle_event":"dev",
   "npm_package_keywords_21":"generator",
   "npm_package_keywords_7":"koa",
   "npm_package_devDependencies_karma_mocha":"^0.1.10",
   "npm_package_devDependencies_jscs":"^1.12.0",
   "npm_package_devDependencies_chai":"^2.2.0",
   "EDITOR":"vim",
   "npm_config_save":"",
   "npm_config_editor":"vim",
   "npm_package_keywords_0":"react",
   "npm_package_dependencies_react_intl":"^1.2.0",
   "npm_package_repository_type":"git",
   "npm_package_name":"isomorphic-flux-boilerplate",
   "LANG":"en_US.UTF-8",
   "npm_config_tag":"latest",
   "npm_package_keywords_1":"flux",
   "npm_config_global":"",
   "npm_package_keywords_24":"intl",
   "npm_package_keywords_2":"alt",
   "npm_package_dependencies_koa_cash":"^1.0.1",
   "npm_package_scripts_build":"webpack --progress --stats --config ./webpack/prod.config.js",
   "npm_config_optional":"true",
   "npm_package_keywords_3":"iso",
   "XPC_FLAGS":"0x0",
   "npm_config_force":"",
   "npm_config_bin_links":"true",
   "npm_package_devDependencies_react_a11y":"git://github.com/iam4x/react-a11y.git#packaged",
   "npm_package_devDependencies_karma_webpack":"^1.5.0",
   "npm_config_searchopts":"",
   "npm_package_dependencies_classnames":"^1.2.0",
   "npm_config_depth":"Infinity",
   "npm_package_main":"server/index.js",
   "npm_config_searchsort":"name",
   "npm_config_rebuild_bundle":"true",
   "npm_package_devDependencies_del":"^1.1.1",
   "npm_package_dependencies_blocked":"^1.1.0",
   "npm_package_version":"0.2.0",
   "XPC_SERVICE_NAME":"0",
   "npm_config_unicode":"true",
   "npm_package_keywords_8":"webpack",
   "npm_package_dependencies_iso":"^4.0.2",
   "npm_package_keywords_9":"jsx",
   "npm_package_dependencies_koa_favicon":"^1.2.0",
   "SHLVL":"2",
   "HOME":"/Users/rdg",
   "npm_config_fetch_retry_maxtimeout":"60000",
   "npm_package_scripts_test":"karma start --single-run",
   "npm_config_strict_ssl":"true",
   "npm_config_save_prefix":"^",
   "npm_config_loglevel":"warn",
   "npm_config_ca":"",
   "npm_package_devDependencies_karma_cli":"0.0.4",
   "npm_config_save_exact":"",
   "npm_config_group":"20",
   "npm_config_fetch_retry_factor":"10",
   "npm_config_dev":"",
   "npm_package_engines_iojs":"^1.7.0",
   "npm_package_devDependencies_babel_eslint":"^3.0.0",
   "npm_config_version":"",
   "npm_config_cache_lock_stale":"60000",
   "npm_package_devDependencies_karma_firefox_launcher":"^0.1.4",
   "npm_package_devDependencies_imagemin":"^3.1.0",
   "npm_config_cache_min":"10",
   "npm_config_searchexclude":"",
   "npm_config_cache":"/Users/rdg/.npm",
   "npm_package_devDependencies_image_webpack_loader":"^1.4.0",
   "LOGNAME":"rdg",
   "LESS":"-F -g -i -M -R -S -w -X -z-4",
   "npm_lifecycle_script":"DEBUG=dev,koa node ./webpack/dev-server.js",
   "npm_config_color":"true",
   "npm_package_devDependencies_karma_sourcemap_loader":"^0.3.4",
   "npm_package_dependencies_koa_compressor":"^1.0.3",
   "VISUAL":"vim",
   "npm_config_proxy":"",
   "LC_CTYPE":"UTF-8",
   "LESS_TERMCAP_so":"\u001b[00;47;30m",
   "npm_package_dependencies_react":"^0.13.1",
   "npm_config_save_optional":"",
   "GOPATH":"/Users/rdg/go/",
   "NVM_BIN":"/Users/rdg/.nvm/versions/io.js/v1.6.3/bin",
   "npm_config_ignore_scripts":"",
   "npm_config_user_agent":"npm/2.7.4 node/v1.6.3 darwin x64",
   "BROWSER":"open",
   "NVM_IOJS_ORG_MIRROR":"https://iojs.org/dist",
   "npm_config_cache_lock_wait":"10000",
   "npm_package_devDependencies_react_hot_loader":"^1.1.4",
   "npm_config_production":"",
   "npm_package_devDependencies_browser_sync":"^2.5.3",
   "npm_package_dependencies_modularized_normalize_scss":"git://github.com/hail2u/normalize.scss.git",
   "DISPLAY":"/private/tmp/com.apple.launchd.ik9VqQQMas/org.macosforge.xquartz:0",
   "npm_config_save_bundle":"",
   "npm_package_tags_24":"intl",
   "npm_config_umask":"0022",
   "npm_config_init_version":"1.0.0",
   "npm_package_tags_23":"i18n",
   "npm_package_devDependencies_esprima_fb":"^14001.1.0-dev-harmony-fb",
   "npm_config_scope":"",
   "npm_config_init_author_name":"",
   "npm_config_git":"git",
   "npm_package_tags_22":"es7",
   "npm_package_devDependencies_node_sass":"^2.0.1",
   "npm_package_devDependencies_css_loader":"^0.10.1",
   "SECURITYSESSIONID":"186d1",
   "npm_config_unsafe_perm":"true",
   "npm_config_tmp":"/var/folders/dm/mw0ts40n7nj8nks0sg41hc500000gn/T",
   "npm_config_onload_script":"",
   "npm_package_tags_21":"generator",
   "npm_package_dependencies_react_router":"^0.13.2",
   "npm_node_execpath":"/Users/rdg/.nvm/versions/io.js/v1.6.3/bin/iojs",
   "npm_config_link":"",
   "npm_config_prefix":"/Users/rdg/.node",
   "npm_package_tags_20":"server",
   "npm_package_devDependencies_eslint_plugin_react":"^2.1.0",
   "LESS_TERMCAP_se":"\u001b[0m",
   "_":"/Users/rdg/.nvm/versions/io.js/v1.6.3/bin/node",
   "NODE_PATH":"app"
}
```

**Comment by cl1ck** [comment]
sorry, thought you meant `process.env`... here you go:
```
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/zsh
TERM=xterm-256color
TMPDIR=/var/folders/dm/mw0ts40n7nj8nks0sg41hc500000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.uX0WZ6xqNW/Render
TERM_PROGRAM_VERSION=343.7
TERM_SESSION_ID=0626B7CD-5F90-4EBC-9EAA-11C75F200F57
USER=rdg
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.78Pkqj7KFw/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/Users/rdg/.nvm/versions/io.js/v1.6.3/bin:/usr/local/bin:/usr/local/sbin:/Users/rdg/bin:/Users/rdg/.node/bin:/Users/rdg/.composer/vendor/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/MAMP/bin/php/php5.5.10/bin:/opt/X11/bin:/usr/local/git/bin
PWD=/Users/rdg/repos/isoflux
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/rdg
LOGNAME=rdg
LC_CTYPE=UTF-8
DISPLAY=/private/tmp/com.apple.launchd.ik9VqQQMas/org.macosforge.xquartz:0
SECURITYSESSIONID=186d1
OLDPWD=/Users/rdg/repos/checkin
BROWSER=open
EDITOR=vim
VISUAL=vim
PAGER=less
LANG=en_US.UTF-8
LESS=-F -g -i -M -R -S -w -X -z-4
GOPATH=/Users/rdg/go/
LESS_TERMCAP_mb=
LESS_TERMCAP_md=
LESS_TERMCAP_me=
LESS_TERMCAP_se=
LESS_TERMCAP_so=
LESS_TERMCAP_ue=
LESS_TERMCAP_us=
LSCOLORS=exfxcxdxbxGxDxabagacad
LS_COLORS=di=34:ln=35:so=32:pi=33:ex=31:bd=36;01:cd=33;01:su=31;40;07:sg=36;40;07:tw=32;40;07:ow=33;40;07:
GREP_COLOR=37;45
GREP_COLORS=mt=37;45
NVM_DIR=/Users/rdg/.nvm
NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist
NVM_IOJS_ORG_MIRROR=https://iojs.org/dist
NVM_IOJS_ORG_VERSION_LISTING=https://iojs.org/dist/index.tab
MANPATH=/Users/rdg/.nvm/versions/io.js/v1.6.3/share/man:/usr/local/share/man:/Users/rdg/.node/share/man:/usr/share/man:/opt/X11/share/man:/usr/local/git/share/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man
NVM_PATH=/Users/rdg/.nvm/versions/io.js/v1.6.3/lib/node
NVM_BIN=/Users/rdg/.nvm/versions/io.js/v1.6.3/bin
COMP_WORDBREAKS=
_=/usr/bin/env
```

**Comment by iam4x** [comment]
`BROWSER=open` is the culprit, I have found a workaround.

Checkout `fix-browser-env-on-server` branch and tell if it's good!

**Comment by cl1ck** [comment]
Did work :+1:  Many thanks, great job!

**Comment by iam4x** [comment]
Cool :tada:
