### ISSUE TITLE
Cannot start development server

### ISSUE THREAD

**Issue by dantetwc** [iam4x/isomorphic-flux-boilerplate#337]
`➜  app git:(master) ✗ npm run dev 

> isomorphic-flux-boilerplate@15.0.0 dev /Users/Dante/Desktop/app
> babel-node ./webpack/dev-server.js

/Users/Dante/Desktop/app/node_modules/babel-preset-save/node_modules/modify-babel-preset/index.js:91
                p._original_name = key;
                                 ^

TypeError: Cannot set property '_original_name' of undefined
    at /Users/Dante/Desktop/app/node_modules/babel-preset-save/node_modules/modify-babel-preset/index.js:91:22
    at Array.forEach (native)
    at module.exports (/Users/Dante/Desktop/app/node_modules/babel-preset-save/node_modules/modify-babel-preset/index.js:77:29)
    at Object.<anonymous> (/Users/Dante/Desktop/app/node_modules/babel-preset-save/index.js:3:35)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js](/Users/Dante/.nvm/versions/node/v4.4.3/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/Dante/.nvm/versions/node/v4.4.3/bin/node" "/Users/Dante/.nvm/versions/node/v4.4.3/bin/npm" "run" "dev"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! isomorphic-flux-boilerplate@15.0.0 dev: `babel-node ./webpack/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the isomorphic-flux-boilerplate@15.0.0 dev script 'babel-node ./webpack/dev-server.js'.
npm ERR! This is most likely a problem with the isomorphic-flux-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node ./webpack/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs isomorphic-flux-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls isomorphic-flux-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Dante/Desktop/app/npm-debug.log`

**Comment by renatopeterman** [comment]
Hi!
I had the same problem, try reinstalling and running with `npm3`:
```
$ npm i -g npm3
$ npm3 run dev
```
It works for me here.

**Comment by EugeneHlushko** [comment]
Try going with `yarn` now.

**Comment by EugeneHlushko** [comment]
Closing this for now, please add any more details if you still have problems.

**Comment by dusnoki** [comment]
I'm having the same issue at the moment

Windows 10 with Linux Bash Implementation
```
dusnoki@E530:/mnt/f/code/isomorphic-flux-boilerplate$ sudo npm run dev

> isomorphic-flux-boilerplate@15.0.0 dev /mnt/f/code/isomorphic-flux-boilerplate
> babel-node ./internals/webpack/dev-server.js

/mnt/f/code/isomorphic-flux-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:334
        throw e;
        ^

TypeError: Cannot set property '_original_name' of undefined (While processing preset: "/mnt/f/code/isomorphic-flux-boilerplate/node_modules/babel-preset-save/index.js")
    at /mnt/f/code/isomorphic-flux-boilerplate/node_modules/babel-preset-save/node_modules/modify-babel-preset/index.js:91:22
    at Array.forEach (native)
    at module.exports (/mnt/f/code/isomorphic-flux-boilerplate/node_modules/babel-preset-save/node_modules/modify-babel-preset/index.js:77:29)
    at Object.<anonymous> (/mnt/f/code/isomorphic-flux-boilerplate/node_modules/babel-preset-save/index.js:3:35)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/mnt/f/code/isomorphic-flux-boilerplate/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Linux 3.4.0+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v4.7.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! isomorphic-flux-boilerplate@15.0.0 dev: `babel-node ./internals/webpack/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the isomorphic-flux-boilerplate@15.0.0 dev script 'babel-node ./internals/webpack/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the isomorphic-flux-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node ./internals/webpack/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs isomorphic-flux-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls isomorphic-flux-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/f/code/isomorphic-flux-boilerplate/npm-debug.log
```

**Comment by MayasHaddad** [comment]
Hello @dusnoki,

As I don't have a windows 10 environment, could you please make sure that [this](https://github.com/iam4x/isomorphic-flux-boilerplate/tree/fix-win10-dev-env) fixes your issue? 🙏

If so, I'll create a PR to merge it to master.
