### ISSUE TITLE
Use with node

### ISSUE THREAD

**Issue by adamjv90** [iam4x/isomorphic-flux-boilerplate#36]
Is there any modification I can make to this setup to be able to run with node instead of iojs?

**Comment by iam4x** [comment]
Haven't tried with `node 0.12.x` yet, I'll give it a shot

**Comment by adamjv90** [comment]
when attempting to 
```bash
npm run dev
```
with node 0.12.2, app exited with the following error
```
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/adam/.nvm/versions/node/v0.12.2/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:133:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/adam/Desktop/weed-app/server/koa.js:4:26)
    at Module._compile (module.js:460:26)
```

**Comment by adamjv90** [comment]
so passing node the --harmony option seems to work

**Comment by iam4x** [comment]
Okay pull master:

* running prod: `NODE_ENV=production node --harmony server/index.js`
* running dev: `node --harmony webpack/dev-server.js`

I'll add note on `README.md`

**Comment by iam4x** [comment]
I've updated the `README.md` is it working for you?

**Comment by adamjv90** [comment]
yes, supplying the harmony option like above works. Also the harmony option is voided by iojs so modifying package.json to

```
"dev": "node --harmony ./webpack/dev-server.js",
```

and processes.json to 

```
"node_args": "--max_old_space_size=300 --harmony"
```
As a note there was a typo in preprocesses.json
```
nord_args": "--max_old_space_size=300"
```

should be 

```
"node_args": "--max_old_space_size=300"
```

**Comment by iam4x** [comment]
You are correct, you wan't to drop a PR to clean this?

**Comment by iam4x** [comment]
#37 merged
