### ISSUE TITLE
core-js error

### ISSUE THREAD

**Issue by subpublicanders** [iam4x/isomorphic-flux-boilerplate#46]
Hello, trying to "npm run dev" on latest master with node 0.12.2. But getting a error.

node --harmony ./webpack/dev-server.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'core-js/shim'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/subpublic/Documents/jobb/rnd/rnd_node/react/isomorphic-flux-boilerplate/node_modules/babel-core/lib/babel/polyfill.js:3:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by iam4x** [comment]
Is it related to https://github.com/webpack/webpack/issues/784 ?

**Comment by iam4x** [comment]
Any update @subpublicanders ?
