### ISSUE TITLE
Server restarts on each file change -> EADDRINUSE

### ISSUE THREAD

**Issue by jonaswindey** [iam4x/isomorphic-flux-boilerplate#80]
When changing one file I get the following:
```
webpack: bundle is now INVALID.
Time: 1596ms
                                  Asset      Size  Chunks             Chunk Names
  1-453b2687f99276187e87ec26d03e88fc.js    381 kB    1, 3             
                            1h0uCyf.eot   21.4 kB                     
                            2J_BsMc.ttf   45.3 kB                     
                           3sk6Jfr.woff     25 kB                     
                            V2d-uc_.png     49 kB                     
app-46eab74b7c0b33de78849d21ea3fac3c.js   4.88 MB       0  [emitted]  app
                            YXLsN8c.svg   71.8 kB                     
  2-f19441f78ad604ad2843358e8955a382.js    376 kB    2, 4             
  3-0a08dafb4a602ece0bf24d0d208e5d94.js   3.64 kB       3             
  4-83fc841ec3d30afd41fe80f3372292ff.js   3.59 kB       4             
   0.4b5b92778ef8a39bed15.hot-update.js   14.7 kB       0  [emitted]  app
   4b5b92778ef8a39bed15.hot-update.json  36 bytes          [emitted]  

WARNING in ./app/components/users.jsx

/Users/jonas/Development/sandbox/app/app/components/users.jsx
  33:4  warning  Unexpected console statement  no-console

✖ 1 problem (0 errors, 1 warning)

webpack: bundle is now VALID.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at Application.app.listen (/Users/jonas/Development/sandbox/app/node_modules/koa/lib/application.js:70:24)
    at Object.<anonymous> (/Users/jonas/Development/sandbox/app/server/koa.js:69:5)
    at Module._compile (module.js:460:26)
    at normalLoader (/Users/jonas/Development/sandbox/app/node_modules/babel-core/lib/babel/api/register/node.js:166:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jonas/Development/sandbox/app/node_modules/babel-core/lib/babel/api/register/node.js:179:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jonas/Development/sandbox/app/server/index.js:17:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
``` 
After that, I have to refresh my page and it's working again.
It seems that the file watcher reloads both the koa webserver and the webpack development server. It should only do the latter.

NodeJS v0.12.4

**Comment by iam4x** [comment]
@jonaswindey Should be fixed now :+1:

**Comment by jonaswindey** [comment]
Great job, you're the boss.

**Comment by jonaswindey** [comment]
Another related question, at the moment, we only watch changes under /server except for the webpack-stats.json file.

This means however that when we change something to a store or action file,the server doesn't reload. When we refresh our browser, the server generates a new version, but it isn't restarted so it takes the old stores file.

I think este (https://github.com/steida/este) solved this by restarting the server without the browser being restarted. Do you think that's an option?

**Comment by iam4x** [comment]
@jonaswindey Yes, it's a nice way to handle this. Thank's for example I'll add this ;)
