### ISSUE TITLE
Error: `libsass` bindings not found. Try reinstalling `node-sass`?

### ISSUE THREAD

**Issue by octopitus** [iam4x/isomorphic-flux-boilerplate#9]
Hi,
I tried to run `npm run dev` and got errors: 

```
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/home/octopitus/projects/app/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/home/octopitus/projects/app/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:410:26)
    at Module._extensions..js (module.js:428:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/octopitus/projects/app/node_modules/babel/lib/babel/api/register/node.js:130:7)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/home/octopitus/projects/app/node_modules/sass-loader/index.js:4:12)
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/home/octopitus/projects/app/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/home/octopitus/projects/app/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:410:26)
    at Module._extensions..js (module.js:428:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/octopitus/projects/app/node_modules/babel/lib/babel/api/register/node.js:130:7)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/home/octopitus/projects/app/node_modules/sass-loader/index.js:4:12)
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/home/octopitus/projects/app/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/home/octopitus/projects/app/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:410:26)
    at Module._extensions..js (module.js:428:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/octopitus/projects/app/node_modules/babel/lib/babel/api/register/node.js:130:7)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/home/octopitus/projects/app/node_modules/sass-loader/index.js:4:12)
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/home/octopitus/projects/app/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/home/octopitus/projects/app/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:410:26)
    at Module._extensions..js (module.js:428:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/octopitus/projects/app/node_modules/babel/lib/babel/api/register/node.js:130:7)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/home/octopitus/projects/app/node_modules/sass-loader/index.js:4:12)
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/home/octopitus/projects/app/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/home/octopitus/projects/app/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:410:26)
    at Module._extensions..js (module.js:428:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/octopitus/projects/app/node_modules/babel/lib/babel/api/register/node.js:130:7)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/home/octopitus/projects/app/node_modules/sass-loader/index.js:4:12)
```
Any ideas?

**Comment by iam4x** [comment]
What is your node version? `$ node -v`

**Comment by jaulz** [comment]
Use `npm install node-sass`. Unfortunately for me it was the same and I had to reinstall several node modules manually...

**Comment by iam4x** [comment]
I've just set up a whole new mac, with the latest version of `iojs` I didn't have any problems

**Comment by iam4x** [comment]
I added a note on the README, it's a common issue with `node-sass`. It's hard to have a clean install.
